#!/bin/bash

./tools/android-ndk-r10e/build/tools/make-standalone-toolchain.sh \
--toolchain=arm-linux-androideabi-4.9 \
--stl=gnustl \
--arch=arm \
--ndk-dir=./tools/android-ndk-r10e \
--system=linux-x86_64 \
--package-dir=./tools \
--install-dir=./tools/android-ndk-toolchain \
--platform=android-19
